[package]
name = "indexer-explorer"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
bigdecimal = "=0.1.0"
clap = "3.0.0-beta.1"
diesel = { version = "1.4.4", features = ["postgres", "numeric", "serde_json"] }
dotenv = "0.15.0"
num-traits = "0.2.11"
openssl-probe = { version = "0.1.2" }
r2d2 = "0.8.8"
serde_json = "1.0.55"
tokio = { version = "0.2", features = ["sync", "time"] }
tokio-diesel = "0.3.0"
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer = { git = "https://github.com/nearprotocol/nearcore", rev="8bf9b050e1173aad3d5cdc31de00f3abfb4a0718" }
