[package]
name = "indexer-explorer"
version = "0.2.3"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.11.0-beta.1"
base64 = "0.11"
bigdecimal = "=0.1.0"
clap = "3.0.0-beta.1"
diesel = { version = "1.4.4", features = ["postgres", "numeric", "serde_json"] }
# Using hacky diesel-derive-enum https://github.com/adwhit/diesel-derive-enum/issues/52
diesel-derive-enum = { git = "https://github.com/khorolets/diesel-derive-enum.git", branch = "lookup-hack", features = ["postgres"] }
dotenv = "0.15.0"
futures = "0.3.5"
hex = "0.4"
itertools = "0.9.0"
num-traits = "0.2.11"
openssl-probe = { version = "0.1.2" }
r2d2 = "0.8.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync", "time", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

tokio-diesel = { git = "https://github.com/frol/tokio-diesel", rev = "3aa925cbc19d20763f41116dd26965225882fd48"}
near-indexer = { git = "https://github.com/nearprotocol/nearcore", rev="c2b6ee64eabacaeb4a4c64a06f7025c51722517c" }
near-crypto = { git = "https://github.com/nearprotocol/nearcore", rev="c2b6ee64eabacaeb4a4c64a06f7025c51722517c" }

[dev-dependencies]
# Pin dependency to avoid compilation errors
actix-rt = "=2.0.0-beta.2"
